# Network Monitor Configuration
packet_buffer_size: 2000
scan_interval: 300  # 5 minutes
save_interval: 60   # 1 minute
ports_to_monitor: "1-100,443,3306,3389,5432"
scan_types:
  - QUICK
  - SERVICE

# Logging Configuration
log_level: INFO
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_directory: logs
log_max_size: 10485760  # 10MB
log_backup_count: 5